version: '3.7'

services:
  web:
    build: .
    volumes:
      - .:/code
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - ./config/.env