# Generated by Django 4.1.2 on 2022-10-26 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('color', models.CharField(choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('PINK', 'PINK'), ('WHITE', 'WHITE'), ('BLACK', 'BLACK')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('type_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typenews')),
            ],
        ),
    ]
