# Generated by Django 4.1.2 on 2022-10-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeNews',
            new_name='NewsType',
        ),
        migrations.AlterModelOptions(
            name='newsitem',
            options={'verbose_name_plural': 'News Items'},
        ),
        migrations.AlterModelOptions(
            name='newstype',
            options={'verbose_name_plural': 'News Types'},
        ),
    ]
