# Generated by Django 4.1.2 on 2022-10-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_typenews_newstype_alter_newsitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsitem',
            old_name='type_news',
            new_name='news_type',
        ),
        migrations.RenameField(
            model_name='newstype',
            old_name='color',
            new_name='news_type_color',
        ),
        migrations.RenameField(
            model_name='newstype',
            old_name='name',
            new_name='news_type_name',
        ),
    ]
