# Generated by Django 4.1.2 on 2022-10-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_type_news_newsitem_news_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstype',
            old_name='news_type_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='newstype',
            old_name='news_type_name',
            new_name='name',
        ),
    ]
